version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: deploy/Dockerfile.PROD
        container_name: ava
        ports:
            - "8000:8000"
        volumes:
            - ./src/app:/app/app
            - ./src/run.py:/app/run.py
        environment:
            MONGO_URI: ${MONGO_URI}
        restart: unless-stopped

volumes:
    mongo-data:
