version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: deploy/Dockerfile.dev
        container_name: ava_app
        ports:
            - "8000:8000"
        volumes:
            - ./src/app:/app/app
        environment:
            MONGO_URI: mongodb://mongodb:27017/ava
        stdin_open: true
        tty: true
        restart: unless-stopped
        depends_on:
            - mongodb

    mongodb:
        image: mongo:latest
        container_name: mongodb
        ports:
            - "27017:27017"
        volumes:
            - mongo-data:/data/db
        restart: unless-stopped

volumes:
    mongo-data:
