FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy the requirements file
COPY ../src/requirements.txt .

# Install production dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application code
COPY ../src/run.py /app
COPY ../src/app/ /app/app

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "run.py"]